timezone: Asia/Almaty
admins:
- '7422963573'
managers:
  Алена: '188939016'
  Оксана: '1446255940'
  Магира: '735574334'
  Ергали: '756622791'
  Арман: ''
synonyms:
  Алена:
  - Алена 1
  - Алена-1
  - Алена_01
  - алена
  Оксана:
  - Оксана 1
  - Оксана-1
  - Оксана_01
  - оксана
  Магира:
  - Магира 1
  - Магира-1
  - Магира_01
  - магира
  Ергали:
  - Ергали 1
  - Ергали-1
  - Ергали_01
  - ергали
  Арман:
  - ARMAN_01
  - Арман 1
  - Арман-1
  - арман
