# pattern_config.yaml · v1.0 · 2025-09-02
regex:
  total: "(?:^|\\s)(итог(?:о)?(?:\\s+по)?|всего)\\b"
  meta: "(группировки|показатели|отборы|сортировка|дополнительные\\s+поля)"
  client: "^(?:[А-ЯA-ZЁ]\\s+\\b|ип\\b|тоо\\b|ооо\\b|осоо\\b|частное\\s+лицо\\b|рынок\\b|магаз(?:ин|\\.?)\\b|тц\\b|супермаркет\\b)"
